# Generated by Django 3.1.6 on 2021-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.TextField(max_length="")),
                ("url", models.TextField(default="")),
                ("status", models.IntegerField(default=0)),
                ("result_string", models.TextField(default="")),
                ("vulnerability", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="SubDomains",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", models.TextField(default="")),
                ("csv_path", models.TextField(default="")),
                ("json_path", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Targets",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", models.TextField(default="")),
                ("urls_path", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.TextField(max_length=15, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
