# Generated by Django 3.1.6 on 2021-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledUrls',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField(default='')),
                ('target', models.TextField(default='')),
                ('username', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('username', models.TextField(default='', max_length=15)),
                ('target', models.TextField(default='')),
                ('sub_path', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('result_string', models.TextField(default='')),
                ('vulnerability', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeaders',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('host', models.TextField(default='')),
                ('accept', models.TextField(default='*/*')),
                ('accept_encoding', models.TextField(default='gzip, deflate')),
                ('user_agent', models.TextField(default='Python/3.9 aiohttp/3.7.3')),
                ('body', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseHeaders',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('headers_string', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('target', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='')),
            ],
        ),
    ]
