# Generated by Django 3.1.6 on 2021-03-04 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='lfi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='linux_directory_traversal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='open_redirect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='rce_linux',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='rce_php',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='rfi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='sqli',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='ssti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targets',
            name='windows_directory_traversal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targets',
            name='xss',
            field=models.IntegerField(default=0),
        ),
    ]
