# Generated by Django 3.1.6 on 2021-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="scan_type",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="reports",
            name="scan_session_id",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="reports",
            name="sub_path",
            field=models.TextField(blank=True, default=""),
        ),
    ]
