# Generated by Django 3.1.6 on 2021-02-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
