# Generated by Django 3.1.6 on 2021-02-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0002_auto_20210206_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="user",
            field=models.TextField(max_length=15),
        ),
    ]
