# Generated by Django 3.1.6 on 2021-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0002_auto_20210309_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="form",
            field=models.TextField(blank=True, default=""),
        ),
    ]
