# Generated by Django 2.2.13 on 2021-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan", "0004_auto_20210206_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="url",
            field=models.TextField(default=""),
        ),
    ]
