# Generated by Django 3.1.6 on 2021-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_auto_20210315_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseheaders',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
