# Generated by Django 3.1.6 on 2021-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_auto_20210207_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='user',
        ),
        migrations.AddField(
            model_name='reports',
            name='username',
            field=models.TextField(default='', max_length=15),
        ),
    ]
