# Generated by Django 3.1.6 on 2021-02-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_auto_20210217_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestheaders',
            name='location',
        ),
        migrations.RemoveField(
            model_name='requestheaders',
            name='urls_path',
        ),
        migrations.RemoveField(
            model_name='responseheaders',
            name='csv_path',
        ),
        migrations.RemoveField(
            model_name='responseheaders',
            name='json_path',
        ),
        migrations.RemoveField(
            model_name='responseheaders',
            name='location',
        ),
        migrations.AddField(
            model_name='requestheaders',
            name='accept',
            field=models.TextField(default='*/*'),
        ),
        migrations.AddField(
            model_name='requestheaders',
            name='accept_encoding',
            field=models.TextField(default='gzip, deflate'),
        ),
        migrations.AddField(
            model_name='requestheaders',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requestheaders',
            name='host',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requestheaders',
            name='user_agent',
            field=models.TextField(default='Python/3.9 aiohttp/3.7.3'),
        ),
        migrations.AddField(
            model_name='responseheaders',
            name='headers_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reports',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestheaders',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responseheaders',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
