# Generated by Django 3.1.6 on 2021-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_auto_20210224_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseheaders',
            name='headers_string',
            field=models.TextField(blank=True, default=''),
        ),
    ]
