# Generated by Django 3.1.6 on 2021-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_auto_20210224_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestheaders',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='responseheaders',
            name='headers_string',
            field=models.TextField(default=''),
        ),
    ]
