# Generated by Django 3.1.6 on 2021-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledIPs',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('scan_session_id', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('target', models.TextField(default='')),
                ('ip_address', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('scan_session_id', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField(default='', max_length=15)),
                ('target', models.TextField(default='')),
                ('ip_address', models.TextField(default='')),
                ('port_number', models.TextField(default='')),
                ('port_status', models.TextField(default='')),
                ('port_service', models.TextField(default='')),
            ],
        ),
    ]