# Generated by Django 3.1.6 on 2021-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('target', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('open_ports', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ports',
            name='port_service',
        ),
        migrations.AddField(
            model_name='ports',
            name='port_protocol',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ports',
            name='port_number',
            field=models.IntegerField(default=0),
        ),
    ]
