# Generated by Django 3.1.6 on 2021-03-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0002_add_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='scan_session_id',
            field=models.TextField(default=''),
        ),
    ]
