# Generated by Django 3.1.6 on 2021-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0003_targets_scan_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whoiss',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('scan_session_id', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField(default='', max_length=15)),
                ('target', models.TextField(default='')),
                ('domain_name', models.TextField(default='')),
                ('registrar', models.TextField(default='')),
                ('whois_server', models.TextField(default='')),
                ('referral_url', models.TextField(default='')),
                ('updated_date', models.TextField(default='')),
                ('creation_date', models.TextField(default='')),
                ('expiration_date', models.TextField(default='')),
                ('name_servers', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('emails', models.TextField(default='')),
                ('dnssec', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('org', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('zipcode', models.TextField(default='')),
                ('country', models.TextField(default='')),
            ],
        ),
    ]
