# Generated by Django 3.1.6 on 2021-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0004_whoiss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoiss',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='city',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='country',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='creation_date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='dnssec',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='domain_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='emails',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='expiration_date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='name_servers',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='org',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='referral_url',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='registrar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='state',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='status',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='updated_date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='whois_server',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='whoiss',
            name='zipcode',
            field=models.TextField(default='', null=True),
        ),
    ]
