# Generated by Django 3.1.6 on 2021-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscan', '0008_auto_20210320_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('scan_session_id', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField(default='', max_length=15)),
                ('target', models.TextField(default='')),
                ('txt', models.TextField(blank=True, default='')),
            ],
        ),
    ]
