# Generated by Django 3.1.6 on 2021-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "username",
                    models.TextField(max_length=15, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("datetime", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
